name: Generate TSC Meeting Agenda

on:
  pull_request:
    paths:
      - '.github/workflows/generate-meeting-agendas.yml'
      - '.github/ISSUE_TEMPLATE/meeting-agenda.md'
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  contents: read

jobs:
  meeting:
    runs-on: ubuntu-latest

    steps:
      - name: Webpack TSC Meeting Agenda
        uses: 'pkgjs/meet@v1'
        with:
          issueTitle: 'TSC Meeting <%= date.toZonedDateTimeISO("UTC").toPlainDate().toString() %>'
          token: ${{ secrets.GITHUB_TOKEN }}
          orgs: webpack,webpack-contrib
          agendaLabel: 'tsc-agenda'
          meetingLabels: 'meeting'
          schedules: '2025-05-05T11:00:00.0[America/Chicago]/P2W'
          createWithin: 'P7D'
          issueTemplate: 'meeting-agenda.md'
